/*
-- Query: SELECT * FROM csit314.movie
LIMIT 0, 1000

-- Date: 2023-05-22 23:50
*/
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (1,'Transformers','A war between two races of robots',' Action',150,'image1.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (2,'Superman','The story of a superhero from Krypton',' Action',180,'image2.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (3,'Little Mermaid','A mermaid who dreams of becoming human',' Animation',120,'image3.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (4,'Avengers: Endgame','The epic conclusion of the Avengers saga',' Action',200,'image4.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (5,'Inception','A thief enters people\'s dreams',' Science Fiction',150,'image5.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (6,'The Lion King','A young lion prince\'s journey to reclaim his kingdom',' Animation',120,'image6.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (7,'Titanic','A tragic love story set on a sinking ship',' Drama',180,'image7.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (8,'Jurassic Park','Dinosaurs come to life in a theme park',' Adventure',150,'image8.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (9,'Harry Potter and the Philosopher\'s Stone','A young wizard\'s adventures at Hogwarts',' Fantasy',180,'image9.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (10,'The Dark Knight','The Joker terrorizes Gotham City',' Action',200,'image10.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (11,'Transformers 2','A war between two races of robots',' Action',150,'image11.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (12,'Superman Returns','Superman\'s return to Metropolis',' Action',180,'image12.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (13,'Moana','A young girl sets sail on a daring adventure',' Animation',120,'image13.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (14,'Guardians of the Galaxy','A group of misfits protect the galaxy',' Science Fiction',150,'image14.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (15,'Finding Nemo','A clownfish searches for his missing son',' Animation',120,'image15.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (16,'The Avengers','Superheroes team up to save the world',' Action',200,'image16.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (17,'Toy Story','A story about toys that come to life',' Animation',120,'image17.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (18,'The Shawshank Redemption','A tale of friendship and hope in prison',' Drama',180,'image18.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (19,'The Godfather','The story of a powerful mafia family',' Crime',200,'image19.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (20,'Pulp Fiction','A collection of interconnected crime stories',' Crime',150,'image20.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (21,'Transformers 3','A war between two races of robots',' Action',150,'image21.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (22,'Wonder Woman','A superheroine fights for justice',' Action',180,'image22.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (23,'Frozen','A magical adventure in an icy kingdom',' Animation',120,'image23.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (24,'Interstellar','A journey through space and time',' Science Fiction',150,'image24.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (25,'Beauty and the Beast','A young woman falls in love with a cursed prince',' Animation',120,'image25.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (26,'The Lord of the Rings: The Fellowship of the Ring','A quest to destroy a powerful ring',' Fantasy',180,'image26.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (27,'The Dark Knight Rises','Batman faces a new threat in Gotham City',' Action',200,'image27.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (28,'Transformers 4','A war between two races of robots',' Action',150,'image28.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (29,'Spider-Man','The story of a young superhero with spider-like abilities',' Action',180,'image29.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (30,'Coco','A boy\'s journey to the Land of the Dead',' Animation',120,'image30.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (31,'Gravity','Astronauts stranded in space fight for survival',' Science Fiction',150,'image31.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (32,'Ratatouille','A rat with a passion for cooking',' Animation',120,'image32.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (33,'The Dark Knight Rises','Batman faces a new threat in Gotham City',' Action',200,'image33.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (34,'Transformers 5','A war between two races of robots',' Action',150,'image34.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (35,'Iron Man','The story of a billionaire genius turned superhero',' Action',180,'image35.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (36,'Up','A heartwarming adventure with an old man and a young boy',' Animation',120,'image36.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (37,'Inception','A thief enters people\'s dreams',' Science Fiction',150,'image37.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (38,'The Jungle Book','A young boy raised by animals in the jungle',' Adventure',120,'image38.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (39,'Forrest Gump','The life story of a simple man',' Drama',180,'image39.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (40,'The Matrix','A computer programmer discovers the truth about reality',' Science Fiction',200,'image40.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (41,'Transformers 6','A war between two races of robots',' Action',150,'image41.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (42,'Captain America: The First Avenger','A superhero fights in World War II',' Action',180,'image42.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (43,'Toy Story 2','Toys embark on a rescue mission',' Animation',120,'image43.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (44,'The Martian','An astronaut stranded on Mars fights to survive',' Science Fiction',150,'image44.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (45,'Inside Out','A journey through the emotions of a young girl',' Animation',120,'image45.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (46,'The Dark Knight Rises','Batman faces a new threat in Gotham City',' Action',200,'image46.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (47,'Transformers 7','A war between two races of robots',' Action',150,'image47.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (48,'The Avengers: Age of Ultron','Superheroes battle an artificial intelligence',' Action',180,'image48.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (49,'Finding Dory','A forgetful fish searches for her parents',' Animation',120,'image49.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (50,'The Hunger Games','A dystopian fight for survival',' Adventure',150,'image50.jpg',0);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (51,'Transformers 8','A war between two races of robots',' Action',150,'image51.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (52,'The Incredibles','A family of superheroes saves the day',' Animation',120,'image52.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (53,'The Shawshank Redemption','A tale of friendship and hope in prison',' Drama',180,'image53.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (54,'The Godfather','The story of a powerful mafia family',' Crime',200,'image54.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (55,'Pulp Fiction','A collection of interconnected crime stories',' Crime',150,'image55.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (56,'Transformers 9','A war between two races of robots',' Action',150,'image56.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (57,'Wonder Woman','A superheroine fights for justice',' Action',180,'image57.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (58,'Frozen','A magical adventure in an icy kingdom',' Animation',120,'image58.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (59,'Interstellar','A journey through space and time',' Science Fiction',150,'image59.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (60,'Beauty and the Beast','A young woman falls in love with a cursed prince',' Animation',120,'image60.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (61,'The Lord of the Rings: The Fellowship of the Ring','A quest to destroy a powerful ring',' Fantasy',180,'image61.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (62,'The Dark Knight Rises','Batman faces a new threat in Gotham City',' Action',200,'image62.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (63,'Transformers 10','A war between two races of robots',' Action',150,'image63.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (64,'Spider-Man','The story of a young superhero with spider-like abilities',' Action',180,'image64.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (65,'Coco','A boy\'s journey to the Land of the Dead',' Animation',120,'image65.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (66,'Gravity','Astronauts stranded in space fight for survival',' Science Fiction',150,'image66.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (67,'Ratatouille','A rat with a passion for cooking',' Animation',120,'image67.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (68,'The Dark Knight Rises','Batman faces a new threat in Gotham City',' Action',200,'image68.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (69,'Transformers 11','A war between two races of robots',' Action',150,'image69.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (70,'Iron Man','The story of a billionaire genius turned superhero',' Action',180,'image70.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (71,'Up','A heartwarming adventure with an old man and a young boy',' Animation',120,'image71.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (72,'Inception','A thief enters people\'s dreams',' Science Fiction',150,'image72.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (73,'The Jungle Book','A young boy raised by animals in the jungle',' Adventure',120,'image73.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (74,'Forrest Gump','The life story of a simple man',' Drama',180,'image74.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (75,'The Matrix','A computer programmer discovers the truth about reality',' Science Fiction',200,'image75.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (76,'Transformers 12','A war between two races of robots',' Action',150,'image76.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (77,'Captain America: The First Avenger','A superhero fights in World War II',' Action',180,'image77.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (78,'Toy Story 2','Toys embark on a rescue mission',' Animation',120,'image78.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (79,'The Martian','An astronaut stranded on Mars fights to survive',' Science Fiction',150,'image79.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (80,'Inside Out','A journey through the emotions of a young girl',' Animation',120,'image80.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (81,'The Dark Knight Rises','Batman faces a new threat in Gotham City',' Action',200,'image81.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (82,'Transformers 13','A war between two races of robots',' Action',150,'image82.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (83,'The Avengers: Age of Ultron','Superheroes battle an artificial intelligence',' Action',180,'image83.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (84,'Finding Dory','A forgetful fish searches for her parents',' Animation',120,'image84.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (85,'The Hunger Games','A dystopian fight for survival',' Adventure',150,'image85.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (86,'Transformers 14','A war between two races of robots',' Action',150,'image86.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (87,'The Incredibles','A family of superheroes saves the day',' Animation',120,'image87.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (88,'The Shawshank Redemption','A tale of friendship and hope in prison',' Drama',180,'image88.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (89,'The Godfather','The story of a powerful mafia family',' Crime',200,'image89.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (90,'Pulp Fiction','A collection of interconnected crime stories',' Crime',150,'image90.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (91,'Transformers 15','A war between two races of robots',' Action',150,'image91.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (92,'Wonder Woman','A superheroine fights for justice',' Action',180,'image92.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (93,'Frozen','A magical adventure in an icy kingdom',' Animation',120,'image93.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (94,'Interstellar','A journey through space and time',' Science Fiction',150,'image94.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (95,'Beauty and the Beast','A young woman falls in love with a cursed prince',' Animation',120,'image95.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (96,'The Lord of the Rings: The Fellowship of the Ring','A quest to destroy a powerful ring',' Fantasy',180,'image96.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (97,'The Dark Knight Rises','Batman faces a new threat in Gotham City',' Action',200,'image97.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (98,'Transformers 16','A war between two races of robots',' Action',150,'image98.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (99,'Spider-Man','The story of a young superhero with spider-like abilities',' Action',180,'image99.jpg',1);
INSERT INTO `` (`id`,`title`,`synopsis`,`genre`,`runTime`,`imageURL`,`suspended`) VALUES (100,'Coco','A boy\'s journey to the Land of the Dead',' Animation',120,'image100.jpg',1);
