/*
-- Query: SELECT * FROM csit314.transactionitem
LIMIT 0, 1000

-- Date: 2023-05-23 02:22
*/
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (2,100,1,1,1,'Popcorn(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (3,200,2,2,2,'Popcorn(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (4,300,3,3,3,'Popcorn(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (5,400,4,4,4,'Popcorn(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (6,500,5,5,5,'Popcorn(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (7,600,6,1,6,'Milo(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (8,700,7,2,7,'Milo(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (9,800,8,3,8,'Milo(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (10,900,9,4,9,'Milo(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (11,1000,10,5,10,'Milo(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (12,1100,11,1,11,'Burger(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (13,1200,12,2,12,'Burger(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (14,1300,13,3,13,'Burger(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (15,1400,14,4,14,'Burger(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (16,1500,15,5,15,'Burger(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (17,1600,16,1,16,'Soda(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (18,1700,17,2,17,'Soda(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (19,1800,18,3,18,'Soda(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (20,1900,19,4,19,'Soda(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (21,2000,20,5,20,'Soda(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (22,2100,21,1,21,'Fries(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (23,2200,22,2,22,'Fries(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (24,2300,23,3,23,'Fries(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (25,2400,24,4,24,'Fries(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (26,2500,25,5,25,'Fries(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (27,2600,26,1,26,'Hot Dog(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (28,2700,27,2,27,'Hot Dog(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (29,2800,28,3,28,'Hot Dog(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (30,2900,29,4,29,'Hot Dog(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (31,3000,30,5,30,'Hot Dog(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (32,3100,31,1,31,'Pop(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (33,3200,32,2,32,'Pop(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (34,3300,33,3,33,'Pop(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (35,3400,34,4,34,'Pop(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (36,3500,35,5,35,'Pop(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (37,3600,36,1,36,'Chicken Wings(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (38,3700,37,2,37,'Chicken Wings(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (39,3800,38,3,38,'Chicken Wings(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (40,3900,39,4,39,'Chicken Wings(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (41,4000,40,5,40,'Chicken Wings(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (42,4100,41,1,41,'Ice Cream(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (43,4200,42,2,42,'Ice Cream(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (44,4300,43,3,43,'Ice Cream(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (45,4400,44,4,44,'Ice Cream(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (46,4500,45,5,45,'Ice Cream(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (47,4600,46,1,46,'Coffee(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (48,4700,47,2,47,'Coffee(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (49,4800,48,3,48,'Coffee(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (50,4900,49,4,49,'Coffee(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (51,5000,50,5,50,'Coffee(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (52,5100,51,1,51,'Pizza(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (53,5200,52,2,52,'Pizza(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (54,5300,53,3,53,'Pizza(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (55,5400,54,4,54,'Pizza(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (56,5500,55,5,55,'Pizza(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (57,5600,56,1,56,'Beer(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (58,5700,57,2,57,'Beer(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (59,5800,58,3,58,'Beer(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (60,5900,59,4,59,'Beer(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (61,6000,60,5,60,'Beer(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (62,6100,61,1,61,'Nachos(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (63,6200,62,2,62,'Nachos(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (64,6300,63,3,63,'Nachos(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (65,6400,64,4,64,'Nachos(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (66,6500,65,5,65,'Nachos(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (67,6600,66,1,66,'Tea(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (68,6700,67,2,67,'Tea(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (69,6800,68,3,68,'Tea(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (70,6900,69,4,69,'Tea(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (71,7000,70,5,70,'Tea(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (72,7100,71,1,71,'Sandwich(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (73,7200,72,2,72,'Sandwich(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (74,7300,73,3,73,'Sandwich(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (75,7400,74,4,74,'Sandwich(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (76,7500,75,5,75,'Sandwich(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (77,7600,76,1,76,'Milkshake(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (78,7700,77,2,77,'Milkshake(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (79,7800,78,3,78,'Milkshake(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (80,7900,79,4,79,'Milkshake(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (81,8000,80,5,80,'Milkshake(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (82,8100,81,1,81,'Hot Chocolate(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (83,8200,82,2,82,'Hot Chocolate(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (84,8300,83,3,83,'Hot Chocolate(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (85,8400,84,4,84,'Hot Chocolate(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (86,8500,85,5,85,'Hot Chocolate(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (87,8600,86,1,86,'Cupcake(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (88,8700,87,2,87,'Cupcake(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (89,8800,88,3,88,'Cupcake(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (90,8900,89,4,89,'Cupcake(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (91,9000,90,5,90,'Cupcake(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (92,9100,91,1,91,'Smoothie(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (93,9200,92,2,92,'Smoothie(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (94,9300,93,3,93,'Smoothie(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (95,9400,94,4,94,'Smoothie(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (96,9500,95,5,95,'Smoothie(XL)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (97,9600,96,1,96,'Mocktail(XS)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (98,9700,97,2,97,'Mocktail(S)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (99,9800,98,3,98,'Mocktail(M)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (100,9900,99,4,99,'Mocktail(L)');
INSERT INTO `` (`id`,`paidPrice`,`transactionId`,`quantity`,`fnbId`,`fnbName`) VALUES (101,10000,100,5,100,'Mocktail(XL)');
