/*
-- Query: SELECT * FROM csit314.userprofiles
LIMIT 0, 1000

-- Date: 2023-05-22 21:09
*/
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (1,'Cinema Manager','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (2,'Customer','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (3,'Cinema Owner','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (4,'User Admin','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (5,'Cinema Manager2','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (6,'Cinema Manager3','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (7,'Cinema Manager4','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (8,'Cinema Manager5','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (9,'Cinema Owner2','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (10,'Cinema Owner3','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (11,'Cinema Owner4','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (12,'Cinema Owner5','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (13,'Customer2','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (14,'Customer3','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (15,'Customer4','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (16,'Customer5','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (17,'User Admin2','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (18,'User Admin3','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (19,'User Admin4','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (20,'User Admin5','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (21,'Cinema Manager6','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (22,'Cinema Manager7','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (23,'Cinema Manager8','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (24,'Cinema Manager9','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (25,'Cinema Owner6','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (26,'Cinema Owner7','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (27,'Cinema Owner8','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (28,'Cinema Owner9','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (29,'Customer6','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (30,'Customer7','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (31,'Customer8','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (32,'Customer9','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (33,'User Admin6','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (34,'User Admin7','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (35,'User Admin8','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (36,'User Admin9','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (37,'Cinema Manager10','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (38,'Cinema Manager11','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (39,'Cinema Manager12','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (40,'Cinema Manager13','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (41,'Cinema Owner10','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (42,'Cinema Owner11','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (43,'Cinema Owner12','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (44,'Cinema Owner13','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (45,'Customer10','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (46,'Customer11','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (47,'Customer12','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (48,'Customer13','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (49,'User Admin10','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (50,'User Admin11','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (51,'User Admin12','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (52,'User Admin13','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (53,'Cinema Manager14','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (54,'Cinema Manager15','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (55,'Cinema Manager16','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (56,'Cinema Manager17','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (57,'Cinema Owner14','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (58,'Cinema Owner15','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (59,'Cinema Owner16','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (60,'Cinema Owner17','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (61,'Customer14','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (62,'Customer15','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (63,'Customer16','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (64,'Customer17','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (65,'User Admin14','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (66,'User Admin15','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (67,'User Admin16','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (68,'User Admin17','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (69,'Cinema Manager18','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (70,'Cinema Manager19','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (71,'Cinema Manager20','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (72,'Cinema Manager21','Cinema Manager',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (73,'Cinema Owner18','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (74,'Cinema Owner19','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (75,'Cinema Owner20','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (76,'Cinema Owner21','Cinema Owner',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (77,'Customer18','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (78,'Customer19','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (79,'Customer20','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (80,'Customer21','Customer',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (81,'User Admin18','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (82,'User Admin19','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (83,'User Admin20','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (84,'User Admin21','User Admin',1);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (85,'User Admin22','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (86,'User Admin23','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (87,'User Admin24','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (88,'User Admin25','User Admin',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (89,'Cinema Manager22','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (90,'Cinema Manager23','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (91,'Cinema Manager24','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (92,'Cinema Manager25','Cinema Manager',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (93,'Cinema Owner22','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (94,'Cinema Owner23','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (95,'Cinema Owner24','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (96,'Cinema Owner25','Cinema Owner',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (97,'Customer22','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (98,'Customer23','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (99,'Customer24','Customer',0);
INSERT INTO `` (`id`,`profileName`,`permission`,`suspended`) VALUES (100,'Customer25','Customer',0);
