/*
-- Query: SELECT * FROM csit314.fnb
LIMIT 0, 1000

-- Date: 2023-05-22 20:59
*/
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (1,100,'image1.jpg','Popcorn(XS)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (2,101,'image2.jpg','Popcorn(S)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (3,102,'image3.jpg','Popcorn(M)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (4,103,'image4.jpg','Popcorn(L)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (5,104,'image5.jpg','Popcorn(XL)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (6,105,'image6.jpg','Milo(XS)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (7,106,'image7.jpg','Milo(S)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (8,107,'image8.jpg','Milo(M)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (9,108,'image9.jpg','Milo(L)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (10,109,'image10.jpg','Milo(XL)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (11,110,'image11.jpg','Burger(XS)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (12,111,'image12.jpg','Burger(S)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (13,112,'image13.jpg','Burger(M)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (14,113,'image14.jpg','Burger(L)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (15,114,'image15.jpg','Burger(XL)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (16,115,'image16.jpg','Soda(XS)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (17,116,'image17.jpg','Soda(S)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (18,117,'image18.jpg','Soda(M)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (19,118,'image19.jpg','Soda(L)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (20,119,'image20.jpg','Soda(XL)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (21,120,'image21.jpg','Fries(XS)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (22,121,'image22.jpg','Fries(S)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (23,122,'image23.jpg','Fries(M)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (24,123,'image24.jpg','Fries(L)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (25,124,'image25.jpg','Fries(XL)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (26,125,'image26.jpg','Hot Dog(XS)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (27,126,'image27.jpg','Hot Dog(S)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (28,127,'image28.jpg','Hot Dog(M)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (29,128,'image29.jpg','Hot Dog(L)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (30,129,'image30.jpg','Hot Dog(XL)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (31,130,'image31.jpg','Pop(XS)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (32,131,'image32.jpg','Pop(S)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (33,132,'image33.jpg','Pop(M)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (34,133,'image34.jpg','Pop(L)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (35,134,'image35.jpg','Pop(XL)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (36,135,'image36.jpg','Chicken Wings(XS)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (37,136,'image37.jpg','Chicken Wings(S)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (38,137,'image38.jpg','Chicken Wings(M)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (39,138,'image39.jpg','Chicken Wings(L)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (40,139,'image40.jpg','Chicken Wings(XL)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (41,140,'image41.jpg','Ice Cream(XS)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (42,141,'image42.jpg','Ice Cream(S)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (43,142,'image43.jpg','Ice Cream(M)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (44,143,'image44.jpg','Ice Cream(L)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (45,144,'image45.jpg','Ice Cream(XL)','Food',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (46,145,'image46.jpg','Coffee(XS)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (47,146,'image47.jpg','Coffee(S)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (48,147,'image48.jpg','Coffee(M)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (49,148,'image49.jpg','Coffee(L)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (50,149,'image50.jpg','Coffee(XL)','Beverage',0);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (51,150,'image51.jpg','Pizza(XS)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (52,151,'image52.jpg','Pizza(S)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (53,152,'image53.jpg','Pizza(M)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (54,153,'image54.jpg','Pizza(L)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (55,154,'image55.jpg','Pizza(XL)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (56,155,'image56.jpg','Beer(XS)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (57,156,'image57.jpg','Beer(S)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (58,157,'image58.jpg','Beer(M)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (59,158,'image59.jpg','Beer(L)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (60,159,'image60.jpg','Beer(XL)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (61,160,'image61.jpg','Nachos(XS)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (62,161,'image62.jpg','Nachos(S)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (63,162,'image63.jpg','Nachos(M)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (64,163,'image64.jpg','Nachos(L)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (65,164,'image65.jpg','Nachos(XL)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (66,165,'image66.jpg','Tea(XS)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (67,166,'image67.jpg','Tea(S)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (68,167,'image68.jpg','Tea(M)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (69,168,'image69.jpg','Tea(L)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (70,169,'image70.jpg','Tea(XL)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (71,170,'image71.jpg','Sandwich(XS)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (72,171,'image72.jpg','Sandwich(S)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (73,172,'image73.jpg','Sandwich(M)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (74,173,'image74.jpg','Sandwich(L)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (75,174,'image75.jpg','Sandwich(XL)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (76,175,'image76.jpg','Milkshake(XS)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (77,176,'image77.jpg','Milkshake(S)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (78,177,'image78.jpg','Milkshake(M)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (79,178,'image79.jpg','Milkshake(L)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (80,179,'image80.jpg','Milkshake(XL)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (81,180,'image81.jpg','Hot Chocolate(XS)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (82,181,'image82.jpg','Hot Chocolate(S)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (83,182,'image83.jpg','Hot Chocolate(M)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (84,183,'image84.jpg','Hot Chocolate(L)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (85,184,'image85.jpg','Hot Chocolate(XL)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (86,185,'image86.jpg','Cupcake(XS)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (87,186,'image87.jpg','Cupcake(S)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (88,187,'image88.jpg','Cupcake(M)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (89,188,'image89.jpg','Cupcake(L)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (90,189,'image90.jpg','Cupcake(XL)','Food',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (91,190,'image91.jpg','Smoothie(XS)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (92,191,'image92.jpg','Smoothie(S)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (93,192,'image93.jpg','Smoothie(M)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (94,193,'image94.jpg','Smoothie(L)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (95,194,'image95.jpg','Smoothie(XL)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (96,195,'image96.jpg','Mocktail(XS)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (97,196,'image97.jpg','Mocktail(S)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (98,197,'image98.jpg','Mocktail(M)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (99,198,'image99.jpg','Mocktail(L)','Beverage',1);
INSERT INTO `` (`id`,`currentPrice`,`imageURL`,`name`,`type`,`suspended`) VALUES (100,199,'image100.jpg','Mocktail(XL)','Beverage',1);
