/*
-- Query: SELECT * FROM csit314.hall
LIMIT 0, 1000

-- Date: 2023-05-22 23:51
*/
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (1,'Hall 1','Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (2,'Hall 2','Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (3,'Hall 3','Not Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (4,'Hall 4','Not Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (5,'Hall 5','Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (6,'Hall 6','Not Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (7,'Hall 7','Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (8,'Hall 8','Not Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (9,'Hall 9','Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (10,'Hall 10','Not Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (11,'Hall 11','Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (12,'Hall 12','Not Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (13,'Hall 13','Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (14,'Hall 14','Not Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (15,'Hall 15','Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (16,'Hall 16','Not Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (17,'Hall 17','Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (18,'Hall 18','Not Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (19,'Hall 19','Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (20,'Hall 20','Not Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (21,'Hall 21','Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (22,'Hall 22','Not Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (23,'Hall 23','Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (24,'Hall 24','Not Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (25,'Hall 25','Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (26,'Hall 26','Not Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (27,'Hall 27','Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (28,'Hall 28','Not Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (29,'Hall 29','Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (30,'Hall 30','Not Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (31,'Hall 31','Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (32,'Hall 32','Not Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (33,'Hall 33','Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (34,'Hall 34','Not Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (35,'Hall 35','Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (36,'Hall 36','Not Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (37,'Hall 37','Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (38,'Hall 38','Not Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (39,'Hall 39','Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (40,'Hall 40','Not Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (41,'Hall 41','Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (42,'Hall 42','Not Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (43,'Hall 43','Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (44,'Hall 44','Not Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (45,'Hall 45','Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (46,'Hall 46','Not Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (47,'Hall 47','Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (48,'Hall 48','Not Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (49,'Hall 49','Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (50,'Hall 50','Not Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (51,'Hall 51','Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (52,'Hall 52','Not Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (53,'Hall 53','Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (54,'Hall 54','Not Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (55,'Hall 55','Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (56,'Hall 56','Not Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (57,'Hall 57','Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (58,'Hall 58','Not Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (59,'Hall 59','Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (60,'Hall 60','Not Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (61,'Hall 61','Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (62,'Hall 62','Not Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (63,'Hall 63','Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (64,'Hall 64','Not Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (65,'Hall 65','Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (66,'Hall 66','Not Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (67,'Hall 67','Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (68,'Hall 68','Not Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (69,'Hall 69','Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (70,'Hall 70','Not Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (71,'Hall 71','Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (72,'Hall 72','Not Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (73,'Hall 73','Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (74,'Hall 74','Not Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (75,'Hall 75','Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (76,'Hall 76','Not Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (77,'Hall 77','Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (78,'Hall 78','Not Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (79,'Hall 79','Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (80,'Hall 80','Not Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (81,'Hall 81','Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (82,'Hall 82','Not Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (83,'Hall 83','Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (84,'Hall 84','Not Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (85,'Hall 85','Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (86,'Hall 86','Not Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (87,'Hall 87','Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (88,'Hall 88','Not Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (89,'Hall 89','Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (90,'Hall 90','Not Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (91,'Hall 91','Available',5,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (92,'Hall 92','Not Available',10,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (93,'Hall 93','Available',15,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (94,'Hall 94','Not Available',5,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (95,'Hall 95','Available',10,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (96,'Hall 96','Not Available',15,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (97,'Hall 97','Available',5,15);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (98,'Hall 98','Not Available',10,5);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (99,'Hall 99','Available',15,10);
INSERT INTO `` (`id`,`name`,`status`,`totalRow`,`totalColumn`) VALUES (100,'Hall 100','Not Available',5,5);
