/*
-- Query: SELECT * FROM csit314.useraccounts
LIMIT 0, 1000

-- Date: 2023-05-22 21:13
*/
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (101,'cinemamanager1@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (102,'customer1@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (103,'cinemaowner1@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (104,'useradmin1@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (105,'cinemamanager2@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (106,'customer2@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (107,'cinemaowner2@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (108,'useradmin2@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (109,'cinemamanager3@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (110,'customer3@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (111,'cinemaowner3@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (112,'useradmin3@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (113,'cinemamanager4@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (114,'customer4@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (115,'cinemaowner4@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (116,'useradmin4@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (117,'cinemamanager5@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (118,'customer5@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (119,'cinemaowner5@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (120,'useradmin5@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (121,'cinemamanager6@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (122,'customer6@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (123,'cinemaowner6@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (124,'useradmin6@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (125,'cinemamanager7@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (126,'customer7@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (127,'cinemaowner7@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (128,'useradmin7@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (129,'cinemamanager8@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (130,'customer8@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (131,'cinemaowner8@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (132,'useradmin8@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (133,'cinemamanager9@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (134,'customer9@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (135,'cinemaowner9@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (136,'useradmin9@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (137,'cinemamanager10@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (138,'customer10@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (139,'cinemaowner10@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (140,'useradmin10@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (141,'cinemamanager11@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (142,'customer11@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (143,'cinemaowner11@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (144,'useradmin11@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (145,'cinemamanager12@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (146,'customer12@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (147,'cinemaowner12@gmail.com','a','Cinema Owner',0,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (148,'useradmin12@gmail.com','a','User Admin',0,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (149,'cinemamanager13@gmail.com','a','Cinema Manager',0,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (150,'customer13@gmail.com','a','Customer',0,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (151,'cinemaowner13@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (152,'useradmin13@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (153,'cinemamanager14@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (154,'customer14@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (155,'cinemaowner14@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (156,'useradmin14@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (157,'cinemamanager15@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (158,'customer15@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (159,'cinemaowner15@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (160,'useradmin15@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (161,'cinemamanager16@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (162,'customer16@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (163,'cinemaowner16@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (164,'useradmin16@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (165,'cinemamanager17@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (166,'customer17@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (167,'cinemaowner17@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (168,'useradmin17@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (169,'cinemamanager18@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (170,'customer18@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (171,'cinemaowner18@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (172,'useradmin18@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (173,'cinemamanager19@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (174,'customer19@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (175,'cinemaowner19@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (176,'useradmin19@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (177,'cinemamanager20@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (178,'customer20@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (179,'cinemaowner20@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (180,'useradmin20@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (181,'cinemamanager21@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (182,'customer21@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (183,'cinemaowner21@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (184,'useradmin21@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (185,'cinemamanager22@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (186,'customer22@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (187,'cinemaowner22@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (188,'useradmin22@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (189,'cinemamanager23@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (190,'customer23@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (191,'cinemaowner23@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (192,'useradmin23@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (193,'cinemamanager24@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (194,'customer24@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (195,'cinemaowner24@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (196,'useradmin24@gmail.com','a','User Admin',1,4);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (197,'cinemamanager25@gmail.com','a','Cinema Manager',1,1);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (198,'customer25@gmail.com','a','Customer',1,2);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (199,'cinemaowner25@gmail.com','a','Cinema Owner',1,3);
INSERT INTO `` (`id`,`email`,`password`,`name`,`suspended`,`profileId`) VALUES (200,'useradmin25@gmail.com','a','User Admin',1,4);
